### ISSUE TITLE
Incorrect pinvoke signatures

### ISSUE THREAD

**Issue by dmex** [Impyy/SharpTox#16]
Hello,

I see the following comment in \Toxy-future\Toxy-future\Toxy\Managers\ProfileManager.cs:

>//why does this always return true?!?
>if (data.IsEncrypted)

The Dllimport signatures for all the libtox functions appear to be using the wrong MarshalAs parameter.

Example:
>[return: MarshalAs(UnmanagedType.Bool)]
>internal static extern bool IsDataEncrypted(byte[] data);

Change the MarshalAs parameter to UnmanagedType.I1 as thats how the CLR marshals C-Style (8-bit) BOOLEAN values.

Example:
[return: MarshalAs(UnmanagedType.I1)]
internal static extern bool IsDataEncrypted(byte[] data);

This results in the correct result in my local tests... I'm entirely not sure why the libtox build is compiling their (32bit) bool types as (8bit) BOOLEAN but until they sort that out you'll have to change all your pinvoke signature to use MarshalAs(UnmanagedType.I1).

Hope it helps
-dmex

**Comment by Impyy** [comment]
I wonder why only that function causes an issue though. Anyway, I'll look at it tonight, thanks!

**Comment by dmex** [comment]
I don't think it's just that function. GCC is compiling the libtox bool types as 1 byte while the pinvoke signatures specify the msvc (win32) bool type which is 4 bytes.

The pinvoke IL stub has probably just been fixing up (most of) the return values at runtime.. You'll need to replace nearly all instances of UnmanagedType.Bool with UnmanagedType.I1.

(Offtopic: I also had some issues opening encrypted profiles created by qtox with the ToxEncryptionFunctions.PassKeyDecrypt function. SharpTox will need to use ToxEncryptionFunctions.PassDecrypt to open them successfully)

**Comment by Impyy** [comment]
Should be fixed in a04f8ce855ed64af400107c0e62111bd2977a145. I want to test it with an msvc build of toxcore first before merging it. If it doesn't work, I'll have to greate separate build profiles for msvc I guess.

Also about the ToxEncryption thing, I know about it. If I recall correctly both of those functions randomly segfault on me, not just PassKeyDecrypt, and I have no idea why. But I'll check to make sure.

**Comment by Impyy** [comment]
Created a new issue for the tox encryption functions problem: #17
